// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// LiveRefreshButton creates a refresh button that changes color based on SSE connection status
// The button shows:
// - Green when connected (Live)
// - Yellow when connecting
// - Red when disconnected
// - Gray as default
//
// Usage: Include this button in your page header controls section, then call updateSSEStatus(status)
// from your JavaScript to update the button's appearance based on connection state.
func LiveRefreshButton() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<button id=\"refresh-btn\" onclick=\"manualRefresh()\" class=\"p-2 rounded-lg transition-colors text-gray-400\" title=\"Connecting...\"><svg id=\"refresh-icon\" class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15\"></path></svg></button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// LiveRefreshButtonScript provides the JavaScript function to update the button status
// This should be included once per page that uses the LiveRefreshButton component
func LiveRefreshButtonScript() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<script>\n\t\t// SSE connection status - update refresh button color\n\t\t// Status can be: 'connected', 'connecting', 'disconnected'\n\t\tfunction updateSSEStatus(status) {\n\t\t\tconst btn = document.getElementById('refresh-btn');\n\t\t\tif (!btn) return;\n\n\t\t\t// Remove all status classes\n\t\t\tbtn.classList.remove('text-green-500', 'text-red-500', 'text-yellow-500', 'text-gray-400');\n\n\t\t\t// Add appropriate class and update title\n\t\t\tswitch (status) {\n\t\t\t\tcase 'connected':\n\t\t\t\t\tbtn.classList.add('text-green-500');\n\t\t\t\t\tbtn.title = 'Live - streaming data';\n\t\t\t\t\tbreak;\n\t\t\t\tcase 'connecting':\n\t\t\t\t\tbtn.classList.add('text-yellow-500');\n\t\t\t\t\tbtn.title = 'Connecting...';\n\t\t\t\t\tbreak;\n\t\t\t\tcase 'disconnected':\n\t\t\t\t\tbtn.classList.add('text-red-500');\n\t\t\t\t\tbtn.title = 'Disconnected - click to retry';\n\t\t\t\t\tbreak;\n\t\t\t\tdefault:\n\t\t\t\t\tbtn.classList.add('text-gray-400');\n\t\t\t\t\tbtn.title = 'Connection status unknown';\n\t\t\t}\n\t\t}\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
